export const songs = [
  {
    id: 1,
    name: "Faded",
    singer: "Alan Walker",
    path: "/assets/music/Alan Walker - Faded Mp3 Song Download.mp3",
    image: "/assets/img/Alan-Walker-Faded-Mp3-Song-Download.jpg",
    isPlaying: false,
  },
  {
    id: 2,
    name: "Dark-Horse",
    singer: "Katy Perry",
    path: "/assets/music/Katy Perry - Dark Horse Mp3 Song Download Ft Juicy J.mp3",
    image: "/assets/img/Katy-Perry-Dark-Horse-Mp3-Song-Download-Ft-Juicy-J.jpg",
    isPlaying: false,
  },
  {
    id: 3,
    name: "Sugar",
    singer: "Maroom 5",
    path: "/assets/music/Sugar Mp3 Maroon 5.mp3",
    image: "/assets/img/Maroon-5-–-Sugar-Mp3-Download-Song-2019.jpg",
    isPlaying: false,
  },
  {
    id: 4,
    name: "Synphony",
    singer: "Clean Badit",
    path: "/assets/music/Clean Bandit - Symphony Mp3 Song Download Ft Zara Larsson.mp3",
    image:
      "/assets/img/Clean-Bandit-Symphony-Mp3-Song-Download-Ft-Zara-Larsson.jpg",
    isPlaying: false,
  },
  {
    id: 5,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
  {
    id: 6,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
  {
    id: 7,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
  {
    id: 8,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
  {
    id: 9,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
  {
    id: 10,
    name: "See you again",
    singer: "Charlie Puth and Wiz Khalifa",
    path: "/assets/music/See You Again Mp3 By Charlie Puth and Wiz Khalifa.mp3",
    image: "/assets/img/Wiz-Khalifa-See-You-Again-Mp3-Download.jpg",
    isPlaying: false,
  },
];
